package cn.ms22.learn_spring_mybatis.mapper;

import cn.ms22.learn_spring_mybatis.model.Member;
import cn.ms22.learn_spring_mybatis.model.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    long countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    @Delete({
        "delete from member",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    @Insert({
        "insert into member (pid, generation, ",
        "name, secName, sequence, ",
        "brief, spouse, spouseBrief, ",
        "otherSpouse, otherSpouseBrief, ",
        "misc)",
        "values (#{pid,jdbcType=INTEGER}, #{generation,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{secname,jdbcType=VARCHAR}, #{sequence,jdbcType=VARCHAR}, ",
        "#{brief,jdbcType=VARCHAR}, #{spouse,jdbcType=VARCHAR}, #{spousebrief,jdbcType=VARCHAR}, ",
        "#{otherspouse,jdbcType=VARCHAR}, #{otherspousebrief,jdbcType=VARCHAR}, ",
        "#{misc,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    List<Member> selectByExampleWithRowbounds(MemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    @Select({
        "select",
        "id, pid, generation, name, secName, sequence, brief, spouse, spouseBrief, otherSpouse, ",
        "otherSpouseBrief, misc",
        "from member",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("cn.ms22.learn_spring_mybatis.mapper.MemberMapper.BaseResultMap")
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    @Update({
        "update member",
        "set pid = #{pid,jdbcType=INTEGER},",
          "generation = #{generation,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "secName = #{secname,jdbcType=VARCHAR},",
          "sequence = #{sequence,jdbcType=VARCHAR},",
          "brief = #{brief,jdbcType=VARCHAR},",
          "spouse = #{spouse,jdbcType=VARCHAR},",
          "spouseBrief = #{spousebrief,jdbcType=VARCHAR},",
          "otherSpouse = #{otherspouse,jdbcType=VARCHAR},",
          "otherSpouseBrief = #{otherspousebrief,jdbcType=VARCHAR},",
          "misc = #{misc,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Member record);
}