package cn.ms22.learn_spring_mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class MemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public MemberExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andGenerationIsNull() {
            addCriterion("generation is null");
            return (Criteria) this;
        }

        public Criteria andGenerationIsNotNull() {
            addCriterion("generation is not null");
            return (Criteria) this;
        }

        public Criteria andGenerationEqualTo(String value) {
            addCriterion("generation =", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationNotEqualTo(String value) {
            addCriterion("generation <>", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationGreaterThan(String value) {
            addCriterion("generation >", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationGreaterThanOrEqualTo(String value) {
            addCriterion("generation >=", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationLessThan(String value) {
            addCriterion("generation <", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationLessThanOrEqualTo(String value) {
            addCriterion("generation <=", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationLike(String value) {
            addCriterion("generation like", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationNotLike(String value) {
            addCriterion("generation not like", value, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationIn(List<String> values) {
            addCriterion("generation in", values, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationNotIn(List<String> values) {
            addCriterion("generation not in", values, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationBetween(String value1, String value2) {
            addCriterion("generation between", value1, value2, "generation");
            return (Criteria) this;
        }

        public Criteria andGenerationNotBetween(String value1, String value2) {
            addCriterion("generation not between", value1, value2, "generation");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSecnameIsNull() {
            addCriterion("secName is null");
            return (Criteria) this;
        }

        public Criteria andSecnameIsNotNull() {
            addCriterion("secName is not null");
            return (Criteria) this;
        }

        public Criteria andSecnameEqualTo(String value) {
            addCriterion("secName =", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameNotEqualTo(String value) {
            addCriterion("secName <>", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameGreaterThan(String value) {
            addCriterion("secName >", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameGreaterThanOrEqualTo(String value) {
            addCriterion("secName >=", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameLessThan(String value) {
            addCriterion("secName <", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameLessThanOrEqualTo(String value) {
            addCriterion("secName <=", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameLike(String value) {
            addCriterion("secName like", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameNotLike(String value) {
            addCriterion("secName not like", value, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameIn(List<String> values) {
            addCriterion("secName in", values, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameNotIn(List<String> values) {
            addCriterion("secName not in", values, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameBetween(String value1, String value2) {
            addCriterion("secName between", value1, value2, "secname");
            return (Criteria) this;
        }

        public Criteria andSecnameNotBetween(String value1, String value2) {
            addCriterion("secName not between", value1, value2, "secname");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("sequence is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("sequence is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(String value) {
            addCriterion("sequence =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(String value) {
            addCriterion("sequence <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(String value) {
            addCriterion("sequence >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(String value) {
            addCriterion("sequence >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(String value) {
            addCriterion("sequence <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(String value) {
            addCriterion("sequence <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLike(String value) {
            addCriterion("sequence like", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotLike(String value) {
            addCriterion("sequence not like", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<String> values) {
            addCriterion("sequence in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<String> values) {
            addCriterion("sequence not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(String value1, String value2) {
            addCriterion("sequence between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(String value1, String value2) {
            addCriterion("sequence not between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andBriefIsNull() {
            addCriterion("brief is null");
            return (Criteria) this;
        }

        public Criteria andBriefIsNotNull() {
            addCriterion("brief is not null");
            return (Criteria) this;
        }

        public Criteria andBriefEqualTo(String value) {
            addCriterion("brief =", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefNotEqualTo(String value) {
            addCriterion("brief <>", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefGreaterThan(String value) {
            addCriterion("brief >", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefGreaterThanOrEqualTo(String value) {
            addCriterion("brief >=", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefLessThan(String value) {
            addCriterion("brief <", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefLessThanOrEqualTo(String value) {
            addCriterion("brief <=", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefLike(String value) {
            addCriterion("brief like", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefNotLike(String value) {
            addCriterion("brief not like", value, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefIn(List<String> values) {
            addCriterion("brief in", values, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefNotIn(List<String> values) {
            addCriterion("brief not in", values, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefBetween(String value1, String value2) {
            addCriterion("brief between", value1, value2, "brief");
            return (Criteria) this;
        }

        public Criteria andBriefNotBetween(String value1, String value2) {
            addCriterion("brief not between", value1, value2, "brief");
            return (Criteria) this;
        }

        public Criteria andSpouseIsNull() {
            addCriterion("spouse is null");
            return (Criteria) this;
        }

        public Criteria andSpouseIsNotNull() {
            addCriterion("spouse is not null");
            return (Criteria) this;
        }

        public Criteria andSpouseEqualTo(String value) {
            addCriterion("spouse =", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseNotEqualTo(String value) {
            addCriterion("spouse <>", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseGreaterThan(String value) {
            addCriterion("spouse >", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseGreaterThanOrEqualTo(String value) {
            addCriterion("spouse >=", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseLessThan(String value) {
            addCriterion("spouse <", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseLessThanOrEqualTo(String value) {
            addCriterion("spouse <=", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseLike(String value) {
            addCriterion("spouse like", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseNotLike(String value) {
            addCriterion("spouse not like", value, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseIn(List<String> values) {
            addCriterion("spouse in", values, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseNotIn(List<String> values) {
            addCriterion("spouse not in", values, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseBetween(String value1, String value2) {
            addCriterion("spouse between", value1, value2, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpouseNotBetween(String value1, String value2) {
            addCriterion("spouse not between", value1, value2, "spouse");
            return (Criteria) this;
        }

        public Criteria andSpousebriefIsNull() {
            addCriterion("spouseBrief is null");
            return (Criteria) this;
        }

        public Criteria andSpousebriefIsNotNull() {
            addCriterion("spouseBrief is not null");
            return (Criteria) this;
        }

        public Criteria andSpousebriefEqualTo(String value) {
            addCriterion("spouseBrief =", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefNotEqualTo(String value) {
            addCriterion("spouseBrief <>", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefGreaterThan(String value) {
            addCriterion("spouseBrief >", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefGreaterThanOrEqualTo(String value) {
            addCriterion("spouseBrief >=", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefLessThan(String value) {
            addCriterion("spouseBrief <", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefLessThanOrEqualTo(String value) {
            addCriterion("spouseBrief <=", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefLike(String value) {
            addCriterion("spouseBrief like", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefNotLike(String value) {
            addCriterion("spouseBrief not like", value, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefIn(List<String> values) {
            addCriterion("spouseBrief in", values, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefNotIn(List<String> values) {
            addCriterion("spouseBrief not in", values, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefBetween(String value1, String value2) {
            addCriterion("spouseBrief between", value1, value2, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andSpousebriefNotBetween(String value1, String value2) {
            addCriterion("spouseBrief not between", value1, value2, "spousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspouseIsNull() {
            addCriterion("otherSpouse is null");
            return (Criteria) this;
        }

        public Criteria andOtherspouseIsNotNull() {
            addCriterion("otherSpouse is not null");
            return (Criteria) this;
        }

        public Criteria andOtherspouseEqualTo(String value) {
            addCriterion("otherSpouse =", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseNotEqualTo(String value) {
            addCriterion("otherSpouse <>", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseGreaterThan(String value) {
            addCriterion("otherSpouse >", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseGreaterThanOrEqualTo(String value) {
            addCriterion("otherSpouse >=", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseLessThan(String value) {
            addCriterion("otherSpouse <", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseLessThanOrEqualTo(String value) {
            addCriterion("otherSpouse <=", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseLike(String value) {
            addCriterion("otherSpouse like", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseNotLike(String value) {
            addCriterion("otherSpouse not like", value, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseIn(List<String> values) {
            addCriterion("otherSpouse in", values, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseNotIn(List<String> values) {
            addCriterion("otherSpouse not in", values, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseBetween(String value1, String value2) {
            addCriterion("otherSpouse between", value1, value2, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspouseNotBetween(String value1, String value2) {
            addCriterion("otherSpouse not between", value1, value2, "otherspouse");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefIsNull() {
            addCriterion("otherSpouseBrief is null");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefIsNotNull() {
            addCriterion("otherSpouseBrief is not null");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefEqualTo(String value) {
            addCriterion("otherSpouseBrief =", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefNotEqualTo(String value) {
            addCriterion("otherSpouseBrief <>", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefGreaterThan(String value) {
            addCriterion("otherSpouseBrief >", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefGreaterThanOrEqualTo(String value) {
            addCriterion("otherSpouseBrief >=", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefLessThan(String value) {
            addCriterion("otherSpouseBrief <", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefLessThanOrEqualTo(String value) {
            addCriterion("otherSpouseBrief <=", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefLike(String value) {
            addCriterion("otherSpouseBrief like", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefNotLike(String value) {
            addCriterion("otherSpouseBrief not like", value, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefIn(List<String> values) {
            addCriterion("otherSpouseBrief in", values, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefNotIn(List<String> values) {
            addCriterion("otherSpouseBrief not in", values, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefBetween(String value1, String value2) {
            addCriterion("otherSpouseBrief between", value1, value2, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andOtherspousebriefNotBetween(String value1, String value2) {
            addCriterion("otherSpouseBrief not between", value1, value2, "otherspousebrief");
            return (Criteria) this;
        }

        public Criteria andMiscIsNull() {
            addCriterion("misc is null");
            return (Criteria) this;
        }

        public Criteria andMiscIsNotNull() {
            addCriterion("misc is not null");
            return (Criteria) this;
        }

        public Criteria andMiscEqualTo(String value) {
            addCriterion("misc =", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscNotEqualTo(String value) {
            addCriterion("misc <>", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscGreaterThan(String value) {
            addCriterion("misc >", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscGreaterThanOrEqualTo(String value) {
            addCriterion("misc >=", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscLessThan(String value) {
            addCriterion("misc <", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscLessThanOrEqualTo(String value) {
            addCriterion("misc <=", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscLike(String value) {
            addCriterion("misc like", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscNotLike(String value) {
            addCriterion("misc not like", value, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscIn(List<String> values) {
            addCriterion("misc in", values, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscNotIn(List<String> values) {
            addCriterion("misc not in", values, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscBetween(String value1, String value2) {
            addCriterion("misc between", value1, value2, "misc");
            return (Criteria) this;
        }

        public Criteria andMiscNotBetween(String value1, String value2) {
            addCriterion("misc not between", value1, value2, "misc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table member
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 04 09:40:00 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table member
     *
     * @mbg.generated Mon Oct 04 09:40:00 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}